/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    work: Work;
    about: About;
    contact: Contact;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    work: WorkSelect<false> | WorkSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  heroLogoUpload?: (number | null) | Media;
  /**
   * Fallback external URL. Upload image will be used first when set.
   */
  heroLogo?: string | null;
  heroHeading?: string | null;
  heroCopy?: string | null;
  marqueeProjects?:
    | {
        title: string;
        description: string;
        imageUpload?: (number | null) | Media;
        /**
         * Fallback external URL. Upload image will be used first when set.
         */
        image?: string | null;
        href: string;
        color?: string | null;
        status?: string | null;
        id?: string | null;
      }[]
    | null;
  manifestoTitle?: string | null;
  manifestoVideoUpload?: (number | null) | Media;
  /**
   * Fallback external URL. Upload video will be used first when set.
   */
  manifestoVideo?: string | null;
  manifestoParagraphs?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  featuredTitle?: string | null;
  featuredLinkLabel?: string | null;
  featuredLinkHref?: string | null;
  featuredProjects?:
    | {
        title: string;
        description: string;
        imageUpload?: (number | null) | Media;
        /**
         * Fallback external URL. Upload image will be used first when set.
         */
        image?: string | null;
        href: string;
        color?: string | null;
        status?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work".
 */
export interface Work {
  id: number;
  kickerTitle?: string | null;
  kickerCopy?: string | null;
  workProjects?:
    | {
        title: string;
        description: string;
        imageUpload?: (number | null) | Media;
        /**
         * Fallback external URL. Upload image will be used first when set.
         */
        image?: string | null;
        href: string;
        color?: string | null;
        status?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  kickerTitle?: string | null;
  kickerCopy?: string | null;
  aboutStory?: string | null;
  aboutCollage?:
    | {
        imageUpload?: (number | null) | Media;
        /**
         * Fallback external URL. Upload image will be used first when set.
         */
        image?: string | null;
        className: string;
        id?: string | null;
      }[]
    | null;
  howWeWorkTitle?: string | null;
  howWeWorkParagraphs?:
    | {
        paragraph: string;
        id?: string | null;
      }[]
    | null;
  services?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  industries?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  clients?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  press?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  imageStripHeadingTop?: string | null;
  imageStripHeadingEmphasis?: string | null;
  imageStripHeadingBottom?: string | null;
  aboutStrip?:
    | {
        alt: string;
        imageUpload?: (number | null) | Media;
        /**
         * Fallback external URL. Upload image will be used first when set.
         */
        image?: string | null;
        href?: string | null;
        objectPosition?: string | null;
        dark?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  kickerTitle?: string | null;
  kickerCopy?: string | null;
  contactHeading?: string | null;
  contactEmail?: string | null;
  contactImageUpload?: (number | null) | Media;
  /**
   * Fallback external URL. Upload image will be used first when set.
   */
  contactImage?: string | null;
  contactImageAlt?: string | null;
  socialHeading?: string | null;
  socialLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroLogoUpload?: T;
  heroLogo?: T;
  heroHeading?: T;
  heroCopy?: T;
  marqueeProjects?:
    | T
    | {
        title?: T;
        description?: T;
        imageUpload?: T;
        image?: T;
        href?: T;
        color?: T;
        status?: T;
        id?: T;
      };
  manifestoTitle?: T;
  manifestoVideoUpload?: T;
  manifestoVideo?: T;
  manifestoParagraphs?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  featuredTitle?: T;
  featuredLinkLabel?: T;
  featuredLinkHref?: T;
  featuredProjects?:
    | T
    | {
        title?: T;
        description?: T;
        imageUpload?: T;
        image?: T;
        href?: T;
        color?: T;
        status?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work_select".
 */
export interface WorkSelect<T extends boolean = true> {
  kickerTitle?: T;
  kickerCopy?: T;
  workProjects?:
    | T
    | {
        title?: T;
        description?: T;
        imageUpload?: T;
        image?: T;
        href?: T;
        color?: T;
        status?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  kickerTitle?: T;
  kickerCopy?: T;
  aboutStory?: T;
  aboutCollage?:
    | T
    | {
        imageUpload?: T;
        image?: T;
        className?: T;
        id?: T;
      };
  howWeWorkTitle?: T;
  howWeWorkParagraphs?:
    | T
    | {
        paragraph?: T;
        id?: T;
      };
  services?:
    | T
    | {
        item?: T;
        id?: T;
      };
  industries?:
    | T
    | {
        item?: T;
        id?: T;
      };
  clients?:
    | T
    | {
        item?: T;
        id?: T;
      };
  press?:
    | T
    | {
        item?: T;
        id?: T;
      };
  imageStripHeadingTop?: T;
  imageStripHeadingEmphasis?: T;
  imageStripHeadingBottom?: T;
  aboutStrip?:
    | T
    | {
        alt?: T;
        imageUpload?: T;
        image?: T;
        href?: T;
        objectPosition?: T;
        dark?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  kickerTitle?: T;
  kickerCopy?: T;
  contactHeading?: T;
  contactEmail?: T;
  contactImageUpload?: T;
  contactImage?: T;
  contactImageAlt?: T;
  socialHeading?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}